// Generated by CoffeeScript 2.7.0
(function() {
  var apiPath, httpProxy;

  httpProxy = require('http-proxy');

  apiPath = '/api/v1';

  httpProxy.createServer(function(req, res, proxy) {
    if (req.url.indexOf(apiPath === 0)) {
      proxy.proxyRequest(req, res, {
        host: 'localhost',
        port: 3000
      });
    } else {
      proxy.proxyRequest(req, res, {
        host: 'localhost',
        port: 9000
      });
    }
  }).listen(8000);

  console.log('Starting Server at http://localhost:8000/');

}).call(this);
